// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'7685ea0f633e4c8d3581819e149d729a13d91335df2e43f85caf2a61aafb8cbb'>;
export type ExecutionHash =
  ExecutionHashBase<'ad6b6a95e4fc5da7dafb549cd13b0e0e2505f7c21939865192caa19c23a42611'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Article: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly htmlContent: CodecTypes['pg/text@1']['output'];
      readonly jsonContent: CodecTypes['pg/json@1']['output'];
      readonly coverImg: CodecTypes['pg/text@1']['output'] | null;
      readonly wordCount: CodecTypes['pg/int4@1']['output'];
      readonly readMinutes: CodecTypes['pg/int4@1']['output'];
      readonly status: 'draft' | 'published' | 'archived' | 'scheduled';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly publishedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly archivedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly scheduledAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly deletedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly contentCategoryId: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly ArticleRelation: {
      readonly articleId: CodecTypes['pg/text@1']['output'];
      readonly relatedArticleId: CodecTypes['pg/text@1']['output'];
      readonly sortOrder: CodecTypes['pg/int4@1']['output'];
    };
    readonly ArticleTag: {
      readonly articleId: CodecTypes['pg/text@1']['output'];
      readonly tagId: CodecTypes['pg/text@1']['output'];
    };
    readonly ContentCategory: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly parentId: CodecTypes['pg/text@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly sortOrder: CodecTypes['pg/int4@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly deletedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly ContentTag: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly deletedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly SystemRouter: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly path: CodecTypes['pg/text@1']['output'] | null;
      readonly icon: CodecTypes['pg/text@1']['output'] | null;
      readonly parentId: CodecTypes['pg/text@1']['output'] | null;
      readonly routeType: 'set' | 'group' | 'page' | 'directory' | 'link';
      readonly sortOrder: CodecTypes['pg/int4@1']['output'];
      readonly defaultOpen: CodecTypes['pg/bool@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly scope: 'public' | 'admin';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly deletedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Article: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly htmlContent: CodecTypes['pg/text@1']['input'];
      readonly jsonContent: CodecTypes['pg/json@1']['input'];
      readonly coverImg: CodecTypes['pg/text@1']['input'] | null;
      readonly wordCount: CodecTypes['pg/int4@1']['input'];
      readonly readMinutes: CodecTypes['pg/int4@1']['input'];
      readonly status: 'draft' | 'published' | 'archived' | 'scheduled';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly publishedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly archivedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly scheduledAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly deletedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly contentCategoryId: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly ArticleRelation: {
      readonly articleId: CodecTypes['pg/text@1']['input'];
      readonly relatedArticleId: CodecTypes['pg/text@1']['input'];
      readonly sortOrder: CodecTypes['pg/int4@1']['input'];
    };
    readonly ArticleTag: {
      readonly articleId: CodecTypes['pg/text@1']['input'];
      readonly tagId: CodecTypes['pg/text@1']['input'];
    };
    readonly ContentCategory: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly parentId: CodecTypes['pg/text@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly sortOrder: CodecTypes['pg/int4@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly deletedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly ContentTag: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly deletedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly SystemRouter: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly path: CodecTypes['pg/text@1']['input'] | null;
      readonly icon: CodecTypes['pg/text@1']['input'] | null;
      readonly parentId: CodecTypes['pg/text@1']['input'] | null;
      readonly routeType: 'set' | 'group' | 'page' | 'directory' | 'link';
      readonly sortOrder: CodecTypes['pg/int4@1']['input'];
      readonly defaultOpen: CodecTypes['pg/bool@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly scope: 'public' | 'admin';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly deletedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly article_relations: {
      readonly article_id: CodecTypes['pg/text@1']['output'];
      readonly related_article_id: CodecTypes['pg/text@1']['output'];
      readonly sort_order: CodecTypes['pg/int4@1']['output'];
    };
    readonly article_tags: {
      readonly article_id: CodecTypes['pg/text@1']['output'];
      readonly tag_id: CodecTypes['pg/text@1']['output'];
    };
    readonly articles: {
      readonly archived_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly content_category_id: CodecTypes['pg/text@1']['output'] | null;
      readonly cover_img: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly htmlContent: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly jsonContent: CodecTypes['pg/json@1']['output'];
      readonly published_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly read_minutes: CodecTypes['pg/int4@1']['output'];
      readonly scheduled_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly status: 'draft' | 'published' | 'archived' | 'scheduled';
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly word_count: CodecTypes['pg/int4@1']['output'];
    };
    readonly content_categories: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly is_active: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly parent_id: CodecTypes['pg/text@1']['output'] | null;
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly sort_order: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly content_tags: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly is_active: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly system_routers: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly default_open: CodecTypes['pg/bool@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly icon: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly is_active: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly parent_id: CodecTypes['pg/text@1']['output'] | null;
      readonly path: CodecTypes['pg/text@1']['output'] | null;
      readonly route_type: 'set' | 'group' | 'page' | 'directory' | 'link';
      readonly scope: 'public' | 'admin';
      readonly sort_order: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly article_relations: {
      readonly article_id: CodecTypes['pg/text@1']['input'];
      readonly related_article_id: CodecTypes['pg/text@1']['input'];
      readonly sort_order: CodecTypes['pg/int4@1']['input'];
    };
    readonly article_tags: {
      readonly article_id: CodecTypes['pg/text@1']['input'];
      readonly tag_id: CodecTypes['pg/text@1']['input'];
    };
    readonly articles: {
      readonly archived_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly content_category_id: CodecTypes['pg/text@1']['input'] | null;
      readonly cover_img: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly htmlContent: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly jsonContent: CodecTypes['pg/json@1']['input'];
      readonly published_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly read_minutes: CodecTypes['pg/int4@1']['input'];
      readonly scheduled_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly status: 'draft' | 'published' | 'archived' | 'scheduled';
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly word_count: CodecTypes['pg/int4@1']['input'];
    };
    readonly content_categories: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly is_active: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly parent_id: CodecTypes['pg/text@1']['input'] | null;
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly sort_order: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly content_tags: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly is_active: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly system_routers: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly default_open: CodecTypes['pg/bool@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly icon: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly is_active: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly parent_id: CodecTypes['pg/text@1']['input'] | null;
      readonly path: CodecTypes['pg/text@1']['input'] | null;
      readonly route_type: 'set' | 'group' | 'page' | 'directory' | 'link';
      readonly scope: 'public' | 'admin';
      readonly sort_order: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly article_relations: {
              columns: {
                readonly article_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly related_article_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sort_order: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['article_id', 'related_article_id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'article_relations_article_id_sort_order_idx_dfdc1267';
                  readonly prefix: 'article_relations_article_id_sort_order_idx';
                  readonly columns: readonly ['article_id', 'sort_order'];
                  readonly unique: false;
                },
                {
                  readonly name: 'article_relations_article_id_idx_fafef5f5';
                  readonly prefix: 'article_relations_article_id_idx';
                  readonly columns: readonly ['article_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'article_relations_related_article_id_idx_3c7bd64e';
                  readonly prefix: 'article_relations_related_article_id_idx';
                  readonly columns: readonly ['related_article_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'article_relations';
                    readonly columns: readonly ['article_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'articles';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'article_relations';
                    readonly columns: readonly ['related_article_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'articles';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly article_tags: {
              columns: {
                readonly article_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tag_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['article_id', 'tag_id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'article_tags_tag_id_idx_94b47830';
                  readonly prefix: 'article_tags_tag_id_idx';
                  readonly columns: readonly ['tag_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'article_tags_article_id_idx_fafef5f5';
                  readonly prefix: 'article_tags_article_id_idx';
                  readonly columns: readonly ['article_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'article_tags';
                    readonly columns: readonly ['article_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'articles';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'article_tags';
                    readonly columns: readonly ['tag_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'content_tags';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly articles: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly htmlContent: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly jsonContent: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                };
                readonly cover_img: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly word_count: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly read_minutes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'draft'>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly published_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly archived_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly scheduled_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly content_category_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['slug'] }];
              indexes: readonly [
                {
                  readonly name: 'articles_title_idx_1c94c7b6';
                  readonly prefix: 'articles_title_idx';
                  readonly columns: readonly ['title'];
                  readonly unique: false;
                },
                {
                  readonly name: 'articles_pub_timeline_820e1fee';
                  readonly prefix: 'articles_pub_timeline';
                  readonly columns: readonly ['status', 'deleted_at', 'published_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'articles_cat_pub_timeline_1c670390';
                  readonly prefix: 'articles_cat_pub_timeline';
                  readonly columns: readonly [
                    'content_category_id',
                    'status',
                    'deleted_at',
                    'published_at',
                  ];
                  readonly unique: false;
                },
                {
                  readonly name: 'articles_content_category_id_idx_d2cda588';
                  readonly prefix: 'articles_content_category_id_idx';
                  readonly columns: readonly ['content_category_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'articles';
                    readonly columns: readonly ['content_category_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'content_categories';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly content_categories: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly parent_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly sort_order: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly is_active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['slug'] }];
              indexes: readonly [
                {
                  readonly name: 'content_categories_parent_id_sort_order_idx_e2696ee4';
                  readonly prefix: 'content_categories_parent_id_sort_order_idx';
                  readonly columns: readonly ['parent_id', 'sort_order'];
                  readonly unique: false;
                },
                {
                  readonly name: 'content_categories_is_active_deleted_at_idx_fb20b6d1';
                  readonly prefix: 'content_categories_is_active_deleted_at_idx';
                  readonly columns: readonly ['is_active', 'deleted_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'content_categories_parent_id_idx_ab33b399';
                  readonly prefix: 'content_categories_parent_id_idx';
                  readonly columns: readonly ['parent_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'content_categories';
                    readonly columns: readonly ['parent_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'content_categories';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly content_tags: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly is_active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['slug'] }];
              indexes: readonly [
                {
                  readonly name: 'content_tags_is_active_deleted_at_idx_fb20b6d1';
                  readonly prefix: 'content_tags_is_active_deleted_at_idx';
                  readonly columns: readonly ['is_active', 'deleted_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly system_routers: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly path: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly icon: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly parent_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly route_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sort_order: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly default_open: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly is_active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly scope: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'admin'>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['path'] }];
              indexes: readonly [
                {
                  readonly name: 'system_routers_parent_id_sort_order_idx_e2696ee4';
                  readonly prefix: 'system_routers_parent_id_sort_order_idx';
                  readonly columns: readonly ['parent_id', 'sort_order'];
                  readonly unique: false;
                },
                {
                  readonly name: 'system_routers_is_active_deleted_at_idx_fb20b6d1';
                  readonly prefix: 'system_routers_is_active_deleted_at_idx';
                  readonly columns: readonly ['is_active', 'deleted_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'system_routers_scope_is_active_deleted_at_idx_2f236761';
                  readonly prefix: 'system_routers_scope_is_active_deleted_at_idx';
                  readonly columns: readonly ['scope', 'is_active', 'deleted_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'system_routers_parent_id_idx_ab33b399';
                  readonly prefix: 'system_routers_parent_id_idx';
                  readonly columns: readonly ['parent_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'system_routers';
                    readonly columns: readonly ['parent_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'system_routers';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly ArticleStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['draft', 'published', 'archived', 'scheduled'];
            };
            readonly RouteScope: {
              readonly kind: 'valueSet';
              readonly values: readonly ['public', 'admin'];
            };
            readonly RouteType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['set', 'group', 'page', 'directory', 'link'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly system_routers: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SystemRouter';
    };
    readonly content_categories: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ContentCategory';
    };
    readonly content_tags: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ContentTag';
    };
    readonly articles: { readonly namespace: 'public' & NamespaceId; readonly model: 'Article' };
    readonly article_tags: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ArticleTag';
    };
    readonly article_relations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ArticleRelation';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Article: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly htmlContent: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly jsonContent: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly coverImg: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly wordCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly readMinutes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly publishedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly archivedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly scheduledAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly deletedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly contentCategoryId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly contentCategory: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ContentCategory';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['contentCategoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly contentTags: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ContentTag';
                };
                readonly cardinality: 'N:M';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['article_id'];
                };
                readonly through: {
                  readonly table: 'article_tags';
                  readonly namespaceId: 'public';
                  readonly parentColumns: readonly ['article_id'];
                  readonly childColumns: readonly ['tag_id'];
                  readonly targetColumns: readonly ['id'];
                };
              };
              readonly relatedFrom: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ArticleRelation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['articleId'];
                };
              };
              readonly relatedTo: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ArticleRelation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['relatedArticleId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'articles';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
                readonly slug: { readonly column: 'slug' };
                readonly htmlContent: { readonly column: 'htmlContent' };
                readonly jsonContent: { readonly column: 'jsonContent' };
                readonly coverImg: { readonly column: 'cover_img' };
                readonly wordCount: { readonly column: 'word_count' };
                readonly readMinutes: { readonly column: 'read_minutes' };
                readonly status: { readonly column: 'status' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly publishedAt: { readonly column: 'published_at' };
                readonly archivedAt: { readonly column: 'archived_at' };
                readonly scheduledAt: { readonly column: 'scheduled_at' };
                readonly deletedAt: { readonly column: 'deleted_at' };
                readonly contentCategoryId: { readonly column: 'content_category_id' };
              };
            };
          };
          readonly ArticleRelation: {
            readonly fields: {
              readonly articleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly relatedArticleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sortOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly article: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Article';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['articleId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly relatedArticle: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Article';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['relatedArticleId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'article_relations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly articleId: { readonly column: 'article_id' };
                readonly relatedArticleId: { readonly column: 'related_article_id' };
                readonly sortOrder: { readonly column: 'sort_order' };
              };
            };
          };
          readonly ArticleTag: {
            readonly fields: {
              readonly articleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tagId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly article: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Article';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['articleId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly tag: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ContentTag';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['tagId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'article_tags';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly articleId: { readonly column: 'article_id' };
                readonly tagId: { readonly column: 'tag_id' };
              };
            };
          };
          readonly ContentCategory: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly parentId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sortOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly deletedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly articles: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Article';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['contentCategoryId'];
                };
              };
              readonly children: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ContentCategory';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['parentId'];
                };
              };
              readonly parent: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ContentCategory';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['parentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'content_categories';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly slug: { readonly column: 'slug' };
                readonly parentId: { readonly column: 'parent_id' };
                readonly description: { readonly column: 'description' };
                readonly sortOrder: { readonly column: 'sort_order' };
                readonly isActive: { readonly column: 'is_active' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly deletedAt: { readonly column: 'deleted_at' };
              };
            };
          };
          readonly ContentTag: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly deletedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly articles: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Article';
                };
                readonly cardinality: 'N:M';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tag_id'];
                };
                readonly through: {
                  readonly table: 'article_tags';
                  readonly namespaceId: 'public';
                  readonly parentColumns: readonly ['tag_id'];
                  readonly childColumns: readonly ['article_id'];
                  readonly targetColumns: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'content_tags';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly slug: { readonly column: 'slug' };
                readonly description: { readonly column: 'description' };
                readonly isActive: { readonly column: 'is_active' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly deletedAt: { readonly column: 'deleted_at' };
              };
            };
          };
          readonly SystemRouter: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly path: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly icon: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly parentId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly routeType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sortOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly defaultOpen: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly scope: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly deletedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly children: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SystemRouter';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['parentId'];
                };
              };
              readonly parent: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SystemRouter';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['parentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'system_routers';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly path: { readonly column: 'path' };
                readonly icon: { readonly column: 'icon' };
                readonly parentId: { readonly column: 'parent_id' };
                readonly routeType: { readonly column: 'route_type' };
                readonly sortOrder: { readonly column: 'sort_order' };
                readonly defaultOpen: { readonly column: 'default_open' };
                readonly isActive: { readonly column: 'is_active' };
                readonly scope: { readonly column: 'scope' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly deletedAt: { readonly column: 'deleted_at' };
              };
            };
          };
        };
        readonly enum: {
          readonly RouteType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'set'; readonly value: 'set' },
              { readonly name: 'group'; readonly value: 'group' },
              { readonly name: 'page'; readonly value: 'page' },
              { readonly name: 'directory'; readonly value: 'directory' },
              { readonly name: 'link'; readonly value: 'link' },
            ];
          };
          readonly RouteScope: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'public'; readonly value: 'public' },
              { readonly name: 'admin'; readonly value: 'admin' },
            ];
          };
          readonly ArticleStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'draft'; readonly value: 'draft' },
              { readonly name: 'published'; readonly value: 'published' },
              { readonly name: 'archived'; readonly value: 'archived' },
              { readonly name: 'scheduled'; readonly value: 'scheduled' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'articles';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'cuid2' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'articles';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'content_categories';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'cuid2' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'content_categories';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'content_tags';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'cuid2' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'content_tags';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'system_routers';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'cuid2' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'system_routers';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
