import type { Metadata } from "next";
import { Oxanium, Noto_Sans } from "next/font/google";
import { serverConfig } from "@/config/env/server-env.config";
import "../styles/globals.css";

const oxanium = Oxanium({
  variable: "--font-oxanium",
  subsets: ["latin"],
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title:
    serverConfig.appName +
    (!serverConfig.env.isPro && ` - DEV`),
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: Readonly<React.ReactNode> }) {
  console.log(serverConfig.datasource);
  return (
    <html
      lang="en"
      className={`${oxanium.variable} ${notoSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
