import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../style/globals.css";
import { serverEnvConfig } from "@/config/server-env.config";
import { TooltipProvider } from "@/components/ui/tooltip";
import {QueryClientProvider} from "@tanstack/react-query";
import { getQueryClient } from "@/lib/utils/get-client-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const title = serverEnvConfig.appName + (serverEnvConfig.env.isPro ? "" : `- ${serverEnvConfig.env.nodeEnv}`);

export const metadata: Metadata = {
  title: title,
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  const queryClient = getQueryClient();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <QueryClientProvider client={queryClient}>
          <TooltipProvider>
            {children}
          </TooltipProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
